<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
         http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.gardin</groupId>
    <artifactId>FoodControl</artifactId>
    <version>1.0</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <craftengine.version>26.8</craftengine.version>
    </properties>


    <repositories>

        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>momirealms-repo</id>
            <url>https://repo.momirealms.net/releases/</url>
        </repository>
        <repository>
            <id>xiaomomi's plugins-releases</id>
            <name>XiaoMoMi&#39;s Plugin Repository</name>
            <url>https://repo.momirealms.net/releases</url>
        </repository>
    </repositories>


    <dependencies>

        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.21.11-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.momirealms</groupId>
            <artifactId>craft-engine-core</artifactId>
            <version>${craftengine.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.momirealms</groupId>
            <artifactId>craft-engine-bukkit</artifactId>
            <version>${craftengine.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>


    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.3.0</version>
            </plugin>
        </plugins>
    </build>


</project>
