name: foodValue
version: '1.0-SNAPSHOT'
main: org.gardin.foodcontrol.FoodControl
api-version: '1.21'

commands:
  foodcontrol:
    description: Reload FoodControl config
    usage: /foodControl reload
    permission: FoodControl.admin

permissions:
  foodcontrol.admin:
    default: op